#!/usr/bin/env bash
# Write .env.local from the running local Supabase stack (supabase status -o env).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

if ! command -v supabase >/dev/null 2>&1; then
  echo "error: supabase CLI not found. Install: https://supabase.com/docs/guides/cli" >&2
  exit 1
fi

if ! supabase status -o env >/dev/null 2>&1; then
  echo "error: local Supabase is not running. Run: npm run db:start" >&2
  exit 1
fi

# shellcheck disable=SC1090
eval "$(supabase status -o env)"

OUT="$ROOT/.env.local"
cat >"$OUT" <<EOF
# Generated by scripts/write-local-env.sh — do not commit
# Local Supabase (Docker). Re-run after supabase start / db reset if keys change.

NEXT_PUBLIC_SUPABASE_URL=${API_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}

# Server-only (never expose to the browser)
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
DATABASE_URL=${DB_URL}

# Local tooling
# Studio:  ${STUDIO_URL:-http://127.0.0.1:54323}
# Mailpit: ${MAILPIT_URL:-http://127.0.0.1:54324}
EOF

echo "Wrote $OUT"
echo "  NEXT_PUBLIC_SUPABASE_URL=$API_URL"
echo "  Studio:  ${STUDIO_URL:-http://127.0.0.1:54323}"
echo "  Mailpit: ${MAILPIT_URL:-http://127.0.0.1:54324}"
